if [[ "$PROFILE" == "1" ]]; then
  zmodload zsh/zprof
  zmodload zsh/datetime

  t0=$EPOCHREALTIME
fi

# PATH

export PATH=$HOME/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:./node_modules/.bin:$GOPATH/bin:$PATH

# nvm

export NVM_DIR="$HOME/.nvm"
# This loads nvm
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
# This loads nvm bash_completion
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm" 

export KEYTIMEOUT=1
export DYLD_FORCE_FLAT_NAMESPACE=1

autoload -U zutil      # [1]
autoload -U compinit   # [2]
autoload -U complist   # [3]

# either git or brew is slow here... ~500ms
#plugins=(git brew history-substring-search)

plugins=(git history-substring-search)

# Set ZSH so oh-my-zsh finds its installation
ZSH=~/.oh-my-zsh

# !! slow 450ms :(
source $ZSH/oh-my-zsh.sh

# colors

export CLICOLOR=1
source ~/.my_zsh_theme.sh

# Aliases

alias sz='source ~/.zshrc'
alias vz='vim ~/.zshrc'
alias vv='vim ~/.vimrc'
alias vt='vim ~/.tmux.conf'
alias g='git'
alias v='vim'
alias vi='vim'
alias c='clear'
alias e='exit'
alias l='ls -ltr'
alias ip="ipconfig getifaddr en0 || ipconfig getifaddr en1"
alias weather='curl http://wttr.in/london?m'

# editor

export EDITOR='DYLD_FORCE_FLAT_NAMESPACE=1 /usr/local/bin/vim'
export VISUAL=/usr/local/bin/vim

_trap_exit() { tmux kill-session -t $$; }
trap _trap_exit EXIT
if [ $TERM != 'screen-256color' ]; then
  tmux new-session -s $$;
fi

TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

unsetopt nomatch
unsetopt correct_all


export NODE_PATH=/usr/local/share/npm/lib/node_modules
export NODE_ENV=development

fpath=(/usr/local/share/zsh-completions $fpath)
source /usr/local/opt/zsh-syntax-highlighting/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey -v

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

bindkey -M vicmd '^P' history-substring-search-up
bindkey -M vicmd '^N' history-substring-search-down

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Homebrew Python
export PATH=/usr/local/bin/python:$PATH
PYTHONPATH="$PYTHONPATH:/usr/local/bin/python"

export LC_ALL="en_US.UTF-8"

if [[ "$PROFILE" == "1" ]]; then
  function {
      t1=$EPOCHREALTIME
      startup=$(( t1 - t0 ))
      print "Shell startup time: $startup"
  }
  unset t0
fi
